# Generated by Django 3.2.5 on 2021-07-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_closestpoints_closest_pair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closestpoints',
            old_name='points_submitted',
            new_name='points_string',
        ),
    ]
